service: epub2kindle-uploads

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  bucket: epubs-upload-bucket

provider:
  name: aws
  stage: dev
  region: us-east-2

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        # Set the CORS policy
        BucketName: ${self:custom.bucket}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - 'https://*.amazonaws.com'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
              MaxAge: 3000
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
              MaxAge: 00


  # Print out the name of the bucket that is created
  Outputs:
    UploadBucketArn:
      Value:
         Fn::GetAtt:
          - S3Bucket
          - Arn
      Export:
        Name: ${self:custom.stage}-UploadBucketArn

    UploadBucketName:
      Value:
        Ref: S3Bucket
      Export:
        Name: ${self:custom.stage}-UploadBucket


